
server:
  port: 8180
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # 连接数满后的排队数，默认为100
      accept-count: 1000
      threads:
        # tomcat最大线程数，默认为200
        max: 800
        # Tomcat启动初始化的线程数，默认值10
        min-spare: 100

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/smart_water?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    database: 0

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hohai.component.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


# swagger配置
swagger:
  enable: true
  application-name: 智慧水平台框架接口文档
  application-version: 1.0
  application-description: 用于开发过程中的接口测试
  try-host: http://localhost:${server.port}

  # 防止XSS攻击
xss:
    # 过滤开关
  enabled: true
    # 排除链接（多个用逗号分隔）
  excludes: /system/notice
    # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

